const fs = require('fs');
const path = require('path');

const rawItems = [
  // Page 1
  {
    name: 'Rosuvastatin 5mg Tablets',
    sku: 'ROS-5MG-TAB',
    description: 'HMG-CoA reductase inhibitor (statin) used to lower LDL cholesterol and reduce cardiovascular risk.',
    price: '171.09',
    compareAtPrice: '195.00',
    stockQuantity: 100,
    minStockAlert: 10,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '5mg',
    activeIngredients: 'Rosuvastatin Calcium',
    manufacturer: 'Glenmark',
    categoryName: 'Cardiovascular'
  },
  {
    name: 'Doxycycline 100mg Capsules',
    sku: 'DOX-100-CAP',
    description: 'Tetracycline antibiotic used to treat bacterial infections, acne, respiratory infections, and malaria prophylaxis.',
    price: '23.86',
    compareAtPrice: '28.00',
    stockQuantity: 150,
    minStockAlert: 15,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Capsule',
    strength: '100mg',
    activeIngredients: 'Doxycycline Hyclate',
    manufacturer: 'Accord',
    categoryName: 'Antibiotics'
  },
  {
    name: 'Ferrous Sulfate 200mg Tablets - Pharmaboost',
    sku: 'FER-200-PB',
    description: 'Iron supplement for the prevention and treatment of iron-deficiency anemia.',
    price: '60.00',
    compareAtPrice: '70.00',
    stockQuantity: 200,
    minStockAlert: 20,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '200mg',
    activeIngredients: 'Ferrous Sulfate',
    manufacturer: 'Pharmaboost',
    categoryName: 'Vitamins & Supplements'
  },
  {
    name: 'Ferrous Sulfate 200mg Tablets - Trion Pharma',
    sku: 'FER-200-TRI',
    description: 'Oral iron supplement used to replenish iron stores and combat fatigue in iron-deficiency anemia.',
    price: '29.50',
    compareAtPrice: '35.00',
    stockQuantity: 200,
    minStockAlert: 20,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '200mg',
    activeIngredients: 'Ferrous Sulfate',
    manufacturer: 'Trion Pharma Ltd',
    categoryName: 'Vitamins & Supplements'
  },
  {
    name: 'Spironolactone 25mg Tablets',
    sku: 'SPI-25MG-TAB',
    description: 'Potassium-sparing diuretic and aldosterone antagonist for hypertension, heart failure, and edema.',
    price: '115.00',
    compareAtPrice: '130.00',
    stockQuantity: 100,
    minStockAlert: 10,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '25mg',
    activeIngredients: 'Spironolactone',
    manufacturer: 'Relon Chem',
    categoryName: 'Cardiovascular'
  },
  {
    name: 'Rivaroxaban 20mg Tablets',
    sku: 'RIV-20MG-TAB',
    description: 'Direct oral anticoagulant (DOAC) factor Xa inhibitor for deep vein thrombosis prevention and stroke reduction in AF.',
    price: '33.00',
    compareAtPrice: '40.00',
    stockQuantity: 80,
    minStockAlert: 10,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '20mg',
    activeIngredients: 'Rivaroxaban',
    manufacturer: 'Teva',
    categoryName: 'Cardiovascular'
  },
  {
    name: 'Ramipril 5mg Tablets - Crescent',
    sku: 'RAM-5MG-CRE',
    description: 'ACE inhibitor used to treat high blood pressure, heart failure, and improve survival after myocardial infarction.',
    price: '187.00',
    compareAtPrice: '210.00',
    stockQuantity: 120,
    minStockAlert: 15,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '5mg',
    activeIngredients: 'Ramipril',
    manufacturer: 'Crescent Pharma',
    categoryName: 'Cardiovascular'
  },
  {
    name: 'Bisoprolol 5mg Tablets - Ipca',
    sku: 'BIS-5MG-IPC',
    description: 'Cardioselective beta-1 blocker used in the management of hypertension, angina, and heart failure.',
    price: '18.00',
    compareAtPrice: '22.00',
    stockQuantity: 150,
    minStockAlert: 15,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '5mg',
    activeIngredients: 'Bisoprolol Fumarate',
    manufacturer: 'Ipca Laboratories',
    categoryName: 'Cardiovascular'
  },
  {
    name: 'Benzydamine 0.15% Oromucosal Spray',
    sku: 'BEN-015-SPR',
    description: 'Locally acting NSAID spray providing rapid relief of pain and inflammation in the mouth and throat.',
    price: '82.00',
    compareAtPrice: '95.00',
    stockQuantity: 60,
    minStockAlert: 10,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Oromucosal Spray',
    strength: '0.15%',
    activeIngredients: 'Benzydamine Hydrochloride',
    manufacturer: 'Abdi Farma',
    categoryName: 'Oral Care'
  },
  {
    name: 'Mebeverine 135mg Tablets',
    sku: 'MEB-135-TAB',
    description: 'Direct antispasmodic for smooth muscle relief in irritable bowel syndrome (IBS) and intestinal colic.',
    price: '163.00',
    compareAtPrice: '185.00',
    stockQuantity: 100,
    minStockAlert: 10,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '135mg',
    activeIngredients: 'Mebeverine Hydrochloride',
    manufacturer: 'Milpharm Limited',
    categoryName: 'Gastrointestinal'
  },
  {
    name: 'Water for Injection 10mL Ampoules - Hameln',
    sku: 'WFI-10ML-HAM',
    description: 'Sterile, non-pyrogenic solvent for reconstitution or dilution of injectable medications.',
    price: '68.95',
    compareAtPrice: '80.00',
    stockQuantity: 200,
    minStockAlert: 20,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Injection',
    strength: '10mL',
    activeIngredients: 'Sterile Water for Injection',
    manufacturer: 'Hameln Pharma LTD',
    categoryName: 'Medical Supplies'
  },
  {
    name: 'Midazolam 5mg/mL Injection',
    sku: 'MID-5MG-INJ',
    description: 'Short-acting benzodiazepine injection for procedural sedation, anesthesia induction, and seizure control.',
    price: '348.00',
    compareAtPrice: '390.00',
    stockQuantity: 40,
    minStockAlert: 5,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Injection',
    strength: '5mg/mL',
    activeIngredients: 'Midazolam',
    manufacturer: 'Hameln',
    categoryName: 'Prescription Drugs'
  },
  {
    name: 'Vizhyd 0.1% Eye Drops (10mL)',
    sku: 'VIZ-01-10ML',
    description: 'Lubricating ophthalmic solution with sodium hyaluronate for dry eyes, irritation, and ocular discomfort.',
    price: '146.00',
    compareAtPrice: '165.00',
    stockQuantity: 80,
    minStockAlert: 10,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Eye Drops',
    strength: '0.1% (10mL)',
    activeIngredients: 'Sodium Hyaluronate',
    manufacturer: 'East Midland Pharma LTD',
    categoryName: 'Eye Care'
  },
  {
    name: 'Eyeaze 1% Eye Drops',
    sku: 'EYE-1PCT-DRP',
    description: 'Carbonic anhydrase inhibitor eye drops used to reduce intraocular pressure in glaucoma and ocular hypertension.',
    price: '118.00',
    compareAtPrice: '135.00',
    stockQuantity: 60,
    minStockAlert: 10,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Eye Drops',
    strength: '1%',
    activeIngredients: 'Brinzolamide',
    manufacturer: 'Ridge Pharma',
    categoryName: 'Eye Care'
  },
  {
    name: 'Hylo-Night Eye Ointment',
    sku: 'HYL-NGT-ONT',
    description: 'Preservative-free nighttime ocular ointment with Vitamin A for prolonged dry eye relief during sleep.',
    price: '115.00',
    compareAtPrice: '130.00',
    stockQuantity: 70,
    minStockAlert: 10,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Eye Ointment',
    strength: 'Standard',
    activeIngredients: 'Vitamin A (Retinol Palmitate)',
    manufacturer: 'Ursapharm',
    categoryName: 'Eye Care'
  },
  {
    name: 'Buscopan 20mg/mL Injection',
    sku: 'BUS-20MG-INJ',
    description: 'Antispasmodic injection for acute smooth muscle spasms of gastrointestinal, biliary, and genitourinary tracts.',
    price: '62.02',
    compareAtPrice: '75.00',
    stockQuantity: 100,
    minStockAlert: 10,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Injection',
    strength: '20mg/mL',
    activeIngredients: 'Hyoscine Butylbromide',
    manufacturer: 'Sanofi',
    categoryName: 'Gastrointestinal'
  },
  {
    name: 'Ramipril 10mg Tablets - Noumed',
    sku: 'RAM-10MG-NOU',
    description: 'High-strength ACE inhibitor for blood pressure control and reduction of cardiovascular mortality.',
    price: '185.00',
    compareAtPrice: '210.00',
    stockQuantity: 100,
    minStockAlert: 10,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '10mg',
    activeIngredients: 'Ramipril',
    manufacturer: 'Noumed',
    categoryName: 'Cardiovascular'
  },
  {
    name: 'Fexofenadine 120mg Tablets',
    sku: 'FEX-120-NOU',
    description: 'Non-drowsy second-generation antihistamine for allergic rhinitis, hay fever, and hives.',
    price: '139.00',
    compareAtPrice: '160.00',
    stockQuantity: 120,
    minStockAlert: 15,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '120mg',
    activeIngredients: 'Fexofenadine Hydrochloride',
    manufacturer: 'Noumed',
    categoryName: 'Allergy & Cold'
  },
  {
    name: 'Allopurinol 100mg Tablets',
    sku: 'ALL-100-IPC',
    description: 'Xanthine oxidase inhibitor used for long-term prevention of gout attacks and uric acid kidney stones.',
    price: '17.75',
    compareAtPrice: '22.00',
    stockQuantity: 150,
    minStockAlert: 15,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '100mg',
    activeIngredients: 'Allopurinol',
    manufacturer: 'Ipca Laboratories',
    categoryName: 'Pain Relief'
  },
  {
    name: 'Naproxen 250mg Tablets',
    sku: 'NAP-250-CRE',
    description: 'NSAID providing long-lasting relief from inflammation, musculoskeletal pain, arthritis, and dysmenorrhea.',
    price: '133.00',
    compareAtPrice: '150.00',
    stockQuantity: 120,
    minStockAlert: 15,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '250mg',
    activeIngredients: 'Naproxen',
    manufacturer: 'Crescent Pharma',
    categoryName: 'Pain Relief'
  },
  {
    name: 'Progesterone 100mg Capsules',
    sku: 'PRO-100-ZEN',
    description: 'Micronised bioidentical progesterone for luteal phase support, HRT regimens, and menstrual cycle regulation.',
    price: '151.00',
    compareAtPrice: '175.00',
    stockQuantity: 80,
    minStockAlert: 10,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Capsule',
    strength: '100mg',
    activeIngredients: 'Progesterone',
    manufacturer: 'Zentiva',
    categoryName: 'Women Health'
  },
  {
    name: 'Sodium Bicarbonate Ear Drops',
    sku: 'SOD-BIC-DRP',
    description: 'Gentle ear drops formulated to soften hardened ear wax and facilitate ear syringing or natural clearance.',
    price: '49.00',
    compareAtPrice: '58.00',
    stockQuantity: 100,
    minStockAlert: 10,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Ear Drops',
    strength: '5%',
    activeIngredients: 'Sodium Bicarbonate',
    manufacturer: 'Essential Healthcare',
    categoryName: 'Ear Care'
  },
  {
    name: 'Oxybutynin 5mg Tablets',
    sku: 'OXY-5MG-STR',
    description: 'Anticholinergic bladder relaxant used to treat overactive bladder, urinary urgency, and frequency.',
    price: '131.00',
    compareAtPrice: '150.00',
    stockQuantity: 90,
    minStockAlert: 10,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '5mg',
    activeIngredients: 'Oxybutynin Hydrochloride',
    manufacturer: 'Strides Pharma',
    categoryName: 'Men Health'
  },
  {
    name: 'Cini Optic HA 0.21% Eye Drops',
    sku: 'CIN-021-DRP',
    description: 'High-concentration hyaluronic acid eye drops for intense hydration and sustained ocular surface comfort.',
    price: '131.00',
    compareAtPrice: '150.00',
    stockQuantity: 70,
    minStockAlert: 10,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Eye Drops',
    strength: '0.21%',
    activeIngredients: 'Sodium Hyaluronate',
    manufacturer: 'Pentan Healthcare',
    categoryName: 'Eye Care'
  },
  {
    name: 'Gliclazide 80mg Tablets - Genesis',
    sku: 'GLI-80MG-GEN',
    description: 'Sulfonylurea antidiabetic agent that stimulates insulin secretion in Type 2 Diabetes management.',
    price: '33.20',
    compareAtPrice: '40.00',
    stockQuantity: 150,
    minStockAlert: 15,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '80mg',
    activeIngredients: 'Gliclazide',
    manufacturer: 'Genesis Pharmaceuticals',
    categoryName: 'Diabetes Care'
  },
  {
    name: 'Gliclazide 80mg Tablets - Crescent',
    sku: 'GLI-80MG-CRE',
    description: 'Oral hypoglycemic tablet for glycemic control in non-insulin-dependent Type 2 Diabetes.',
    price: '34.50',
    compareAtPrice: '42.00',
    stockQuantity: 150,
    minStockAlert: 15,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '80mg',
    activeIngredients: 'Gliclazide',
    manufacturer: 'Crescent Pharma',
    categoryName: 'Diabetes Care'
  },
  {
    name: 'Water for Injection 5mL Ampoules - Hameln',
    sku: 'WFI-5ML-HAM',
    description: 'Sterile solvent ampoules for reconstituting lyophilized drugs and compounding injectables.',
    price: '20.06',
    compareAtPrice: '25.00',
    stockQuantity: 250,
    minStockAlert: 25,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Injection',
    strength: '5mL',
    activeIngredients: 'Sterile Water for Injection',
    manufacturer: 'Hameln',
    categoryName: 'Medical Supplies'
  },
  {
    name: 'Paracetamol 500mg Tablets - Zentiva',
    sku: 'PAR-500-ZEN',
    description: 'Essential analgesic and antipyretic for mild to moderate aches, headaches, and fever reduction.',
    price: '33.00',
    compareAtPrice: '40.00',
    stockQuantity: 300,
    minStockAlert: 30,
    requiresPrescription: false,
    isFeatured: true,
    dosageForm: 'Tablet',
    strength: '500mg',
    activeIngredients: 'Paracetamol',
    manufacturer: 'Zentiva',
    categoryName: 'Pain Relief'
  },
  {
    name: 'Paracetamol 500mg Tablets - Crescent',
    sku: 'PAR-500-CRE',
    description: 'Everyday pain and fever relief tablets with reliable rapid absorption.',
    price: '36.30',
    compareAtPrice: '42.00',
    stockQuantity: 300,
    minStockAlert: 30,
    requiresPrescription: false,
    isFeatured: true,
    dosageForm: 'Tablet',
    strength: '500mg',
    activeIngredients: 'Paracetamol',
    manufacturer: 'Crescent Pharma',
    categoryName: 'Pain Relief'
  },
  {
    name: 'Paracetamol 500mg Tablets - Ipca',
    sku: 'PAR-500-IPC',
    description: 'High-quality Paracetamol tablets providing dependable pain and fever relief.',
    price: '10.18',
    compareAtPrice: '14.00',
    stockQuantity: 300,
    minStockAlert: 30,
    requiresPrescription: false,
    isFeatured: true,
    dosageForm: 'Tablet',
    strength: '500mg',
    activeIngredients: 'Paracetamol',
    manufacturer: 'Ipca Laboratories',
    categoryName: 'Pain Relief'
  },
  {
    name: 'Thealoz Duo Eye Drops',
    sku: 'THE-DUO-DRP',
    description: 'Advanced bioprotection & hydration dry eye drops combining Trehalose and Sodium Hyaluronate.',
    price: '198.00',
    compareAtPrice: '225.00',
    stockQuantity: 60,
    minStockAlert: 10,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Eye Drops',
    strength: 'Standard (10mL)',
    activeIngredients: 'Trehalose + Sodium Hyaluronate',
    manufacturer: 'Thea Laboratories',
    categoryName: 'Eye Care'
  },
  {
    name: 'Ventolin Evohaler 100mcg',
    sku: 'VEN-100-EVO',
    description: 'Fast-acting bronchodilator inhaler providing immediate relief from asthma attacks and bronchospasms.',
    price: '91.00',
    compareAtPrice: '105.00',
    stockQuantity: 150,
    minStockAlert: 20,
    requiresPrescription: true,
    isFeatured: true,
    dosageForm: 'Inhaler',
    strength: '100mcg',
    activeIngredients: 'Salbutamol Sulfate',
    manufacturer: 'GlaxoSmithKline (GSK)',
    categoryName: 'Respiratory'
  },
  {
    name: 'Chlorphenamine 4mg Tablets',
    sku: 'CHL-4MG-CRE',
    description: 'First-generation antihistamine for fast relief from allergic reactions, insect bites, chickenpox itching, and urticaria.',
    price: '62.00',
    compareAtPrice: '72.00',
    stockQuantity: 150,
    minStockAlert: 15,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '4mg',
    activeIngredients: 'Chlorphenamine Maleate',
    manufacturer: 'Crescent Pharma',
    categoryName: 'Allergy & Cold'
  },
  {
    name: 'Hylo-Care Eye Drops',
    sku: 'HYL-CAR-DRP',
    description: 'Ophthalmic moisturizing solution with dexpanthenol to support corneal epithelial healing and dry eye relief.',
    price: '195.00',
    compareAtPrice: '220.00',
    stockQuantity: 60,
    minStockAlert: 10,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Eye Drops',
    strength: 'Standard (10mL)',
    activeIngredients: 'Sodium Hyaluronate + Dexpanthenol',
    manufacturer: 'Ursapharm',
    categoryName: 'Eye Care'
  },

  // Page 2
  {
    name: 'Aspirin 75mg Gastro-Resistant Tablets - Almus',
    sku: 'ASP-75MG-ALM',
    description: 'Low-dose enteric-coated antiplatelet aspirin for secondary cardiovascular and stroke prevention.',
    price: '57.00',
    compareAtPrice: '68.00',
    stockQuantity: 200,
    minStockAlert: 20,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '75mg',
    activeIngredients: 'Aspirin (Acetylsalicylic Acid)',
    manufacturer: 'Almus',
    categoryName: 'Cardiovascular'
  },
  {
    name: 'Aspirin 75mg Dispersible Tablets - Aspar',
    sku: 'ASP-75MG-ASP',
    description: 'Dispersible low-dose cardioprotective aspirin providing rapid platelet inhibition.',
    price: '210.25',
    compareAtPrice: '240.00',
    stockQuantity: 150,
    minStockAlert: 15,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '75mg',
    activeIngredients: 'Aspirin (Acetylsalicylic Acid)',
    manufacturer: 'Aspar Pharmaceuticals',
    categoryName: 'Cardiovascular'
  },
  {
    name: 'Amlodipine 5mg Tablets - Sandoz',
    sku: 'AML-5MG-SAN',
    description: 'Dihydropyridine calcium channel blocker for hypertension and chronic stable angina.',
    price: '20.00',
    compareAtPrice: '26.00',
    stockQuantity: 200,
    minStockAlert: 20,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '5mg',
    activeIngredients: 'Amlodipine Besilate',
    manufacturer: 'Sandoz',
    categoryName: 'Cardiovascular'
  },
  {
    name: 'Amlodipine 5mg Tablets - Crescent',
    sku: 'AML-5MG-CRE',
    description: 'Long-acting calcium channel blocker for daily blood pressure control.',
    price: '61.00',
    compareAtPrice: '72.00',
    stockQuantity: 180,
    minStockAlert: 20,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '5mg',
    activeIngredients: 'Amlodipine Besilate',
    manufacturer: 'Crescent Pharma',
    categoryName: 'Cardiovascular'
  },
  {
    name: 'Amlodipine 10mg Tablets - Sandoz',
    sku: 'AML-10MG-SAN',
    description: 'Higher dose calcium channel blocker for resistant hypertension and angina pectoris.',
    price: '14.00',
    compareAtPrice: '18.00',
    stockQuantity: 180,
    minStockAlert: 20,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '10mg',
    activeIngredients: 'Amlodipine Besilate',
    manufacturer: 'Sandoz',
    categoryName: 'Cardiovascular'
  },
  {
    name: 'Ovex Family Pack Tablets (Mebendazole)',
    sku: 'OVX-FAM-PCK',
    description: 'Single-dose family deworming pack containing Mebendazole to treat threadworms and intestinal pinworms.',
    price: '180.00',
    compareAtPrice: '210.00',
    stockQuantity: 80,
    minStockAlert: 10,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '100mg',
    activeIngredients: 'Mebendazole',
    manufacturer: 'McNeil Products Limited',
    categoryName: 'Digestive Health'
  },
  {
    name: 'Brinzolamide 10mg/mL Eye Drops - Sandoz',
    sku: 'BRZ-10MG-SAN',
    description: 'Ophthalmic suspension to lower elevated intraocular pressure in open-angle glaucoma.',
    price: '155.00',
    compareAtPrice: '175.00',
    stockQuantity: 60,
    minStockAlert: 10,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Eye Drops',
    strength: '10mg/mL',
    activeIngredients: 'Brinzolamide',
    manufacturer: 'Sandoz',
    categoryName: 'Eye Care'
  },
  {
    name: 'Empagliflozin 10mg Tablets (Jardiance)',
    sku: 'EMP-10MG-TAB',
    description: 'SGLT2 inhibitor for blood sugar reduction in Type 2 Diabetes and cardiovascular risk reduction in heart failure.',
    price: '778.60',
    compareAtPrice: '850.00',
    stockQuantity: 50,
    minStockAlert: 5,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '10mg',
    activeIngredients: 'Empagliflozin',
    manufacturer: 'Boehringer Ingelheim',
    categoryName: 'Diabetes Care'
  },
  {
    name: 'Hypromellose 0.3% Eye Drops',
    sku: 'HYP-03-DRP',
    description: 'Artificial tears lubricant soothing dry, gritty, and tired eyes caused by screens or wind.',
    price: '75.00',
    compareAtPrice: '88.00',
    stockQuantity: 100,
    minStockAlert: 10,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Eye Drops',
    strength: '0.3%',
    activeIngredients: 'Hypromellose',
    manufacturer: 'Trion Pharma',
    categoryName: 'Eye Care'
  },
  {
    name: 'Olig Ear Drops',
    sku: 'OLI-EAR-DRP',
    description: 'Antimicrobial and astringent ear drops for maintaining ear canal hygiene and preventing swimmer ear.',
    price: '311.00',
    compareAtPrice: '350.00',
    stockQuantity: 50,
    minStockAlert: 5,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Ear Drops',
    strength: 'Standard',
    activeIngredients: 'Acetic Acid / Mineral Solution',
    manufacturer: 'Renascience',
    categoryName: 'Ear Care'
  },
  {
    name: 'Hylo-Night Eye Ointment - Ursa Pharm',
    sku: 'HYL-NGT-URS',
    description: 'Vitamin A enriched nighttime lubricating ointment for overnight corneal protection.',
    price: '115.00',
    compareAtPrice: '130.00',
    stockQuantity: 70,
    minStockAlert: 10,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Eye Ointment',
    strength: 'Standard',
    activeIngredients: 'Vitamin A (Retinol Palmitate)',
    manufacturer: 'Ursapharm',
    categoryName: 'Eye Care'
  },
  {
    name: 'Clarithromycin 500mg Tablets - Sandoz',
    sku: 'CLA-500-SAN',
    description: 'Macrolide antibiotic used for respiratory tract infections, skin infections, and H. pylori eradication.',
    price: '155.00',
    compareAtPrice: '175.00',
    stockQuantity: 100,
    minStockAlert: 10,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '500mg',
    activeIngredients: 'Clarithromycin',
    manufacturer: 'Sandoz',
    categoryName: 'Antibiotics'
  },
  {
    name: 'Atorvastatin 40mg Tablets - Sandoz',
    sku: 'ATO-40MG-SAN',
    description: 'Potent statin therapy for severe hypercholesterolemia and secondary prevention of cardiovascular events.',
    price: '75.00',
    compareAtPrice: '90.00',
    stockQuantity: 120,
    minStockAlert: 15,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '40mg',
    activeIngredients: 'Atorvastatin Calcium',
    manufacturer: 'Sandoz',
    categoryName: 'Cardiovascular'
  },
  {
    name: 'Amitriptyline 10mg Tablets - Flamingo',
    sku: 'AMI-10MG-FLA',
    description: 'Tricyclic agent for neuropathic pain management, migraine prophylaxis, and tension headache prevention.',
    price: '28.00',
    compareAtPrice: '35.00',
    stockQuantity: 100,
    minStockAlert: 10,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '10mg',
    activeIngredients: 'Amitriptyline Hydrochloride',
    manufacturer: 'Flamingo Pharma',
    categoryName: 'Mental Health'
  },
  {
    name: 'Amitriptyline 10mg Tablets - Accord',
    sku: 'AMI-10MG-ACC',
    description: 'Tricyclic medication indicated for chronic nerve pain relief, fibromyalgia, and migraine prevention.',
    price: '8.90',
    compareAtPrice: '12.00',
    stockQuantity: 150,
    minStockAlert: 15,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '10mg',
    activeIngredients: 'Amitriptyline Hydrochloride',
    manufacturer: 'Accord Healthcare',
    categoryName: 'Mental Health'
  },
  {
    name: 'Xailin Night Ointment',
    sku: 'XAI-NGT-ONT',
    description: 'Preservative-free ophthalmic lubricant ointment providing a long-lasting moisture barrier for severe dry eye.',
    price: '74.00',
    compareAtPrice: '85.00',
    stockQuantity: 80,
    minStockAlert: 10,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Eye Ointment',
    strength: '5g',
    activeIngredients: 'White Soft Paraffin + Mineral Oil',
    manufacturer: 'VisuFarma',
    categoryName: 'Eye Care'
  },
  {
    name: 'Metformin 500mg Tablets',
    sku: 'MET-500-GEN',
    description: 'First-line biguanide oral hypoglycemic medication for managing blood glucose in Type 2 Diabetes.',
    price: '27.45',
    compareAtPrice: '34.00',
    stockQuantity: 250,
    minStockAlert: 25,
    requiresPrescription: true,
    isFeatured: true,
    dosageForm: 'Tablet',
    strength: '500mg',
    activeIngredients: 'Metformin Hydrochloride',
    manufacturer: 'Generic',
    categoryName: 'Diabetes Care'
  },
  {
    name: 'Optanol 0.1% Eye Drops (Patanol)',
    sku: 'OPT-01-NOV',
    description: 'Antihistamine and mast cell stabilizer eye drops for treating allergic conjunctivitis and itchy eyes.',
    price: '101.00',
    compareAtPrice: '120.00',
    stockQuantity: 70,
    minStockAlert: 10,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Eye Drops',
    strength: '0.1%',
    activeIngredients: 'Olopatadine Hydrochloride',
    manufacturer: 'Novartis',
    categoryName: 'Eye Care'
  },
  {
    name: 'Empagliflozin 25mg Tablets (Jardiance)',
    sku: 'EMP-25MG-TAB',
    description: 'High-strength SGLT2 inhibitor providing glycemic control, weight benefit, and heart failure protection.',
    price: '766.67',
    compareAtPrice: '840.00',
    stockQuantity: 50,
    minStockAlert: 5,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '25mg',
    activeIngredients: 'Empagliflozin',
    manufacturer: 'Boehringer Ingelheim',
    categoryName: 'Diabetes Care'
  },
  {
    name: 'Apixaban 5mg Tablets (Eliquis Generic)',
    sku: 'API-5MG-SAN',
    description: 'Novel oral factor Xa inhibitor anticoagulant for stroke prevention in non-valvular atrial fibrillation.',
    price: '872.00',
    compareAtPrice: '950.00',
    stockQuantity: 40,
    minStockAlert: 5,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '5mg',
    activeIngredients: 'Apixaban',
    manufacturer: 'Sandoz',
    categoryName: 'Cardiovascular'
  },
  {
    name: 'Cetirizine 10mg Tablets - Indoco',
    sku: 'CET-10MG-IND',
    description: 'Rapid-acting antihistamine for hay fever, allergic rhinitis, and urticarial skin reactions.',
    price: '15.00',
    compareAtPrice: '20.00',
    stockQuantity: 200,
    minStockAlert: 20,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '10mg',
    activeIngredients: 'Cetirizine Hydrochloride',
    manufacturer: 'Indoco Remedies',
    categoryName: 'Allergy & Cold'
  },
  {
    name: 'Cetirizine 10mg Tablets - Crescent',
    sku: 'CET-10MG-CRE',
    description: 'Daily allergy relief tablet targeting sneezing, runny nose, itchy throat, and skin allergies.',
    price: '46.00',
    compareAtPrice: '55.00',
    stockQuantity: 200,
    minStockAlert: 20,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '10mg',
    activeIngredients: 'Cetirizine Hydrochloride',
    manufacturer: 'Crescent Pharma',
    categoryName: 'Allergy & Cold'
  },
  {
    name: 'Esomeprazole 40mg Tablets - Ethypharm',
    sku: 'ESO-40MG-ETH',
    description: 'High-potency proton pump inhibitor (PPI) for healing erosive esophagitis and severe GERD.',
    price: '320.00',
    compareAtPrice: '360.00',
    stockQuantity: 80,
    minStockAlert: 10,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '40mg',
    activeIngredients: 'Esomeprazole Magnesium',
    manufacturer: 'Ethypharm',
    categoryName: 'Gastrointestinal'
  },
  {
    name: 'Quetiapine 25mg Tablets',
    sku: 'QUE-25MG-CRE',
    description: 'Atypical antipsychotic indicated for bipolar disorder, schizophrenia, and adjunct treatment of major depressive episodes.',
    price: '205.00',
    compareAtPrice: '235.00',
    stockQuantity: 60,
    minStockAlert: 10,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '25mg',
    activeIngredients: 'Quetiapine Fumarate',
    manufacturer: 'Crescent Pharma',
    categoryName: 'Mental Health'
  },
  {
    name: 'Germolene Antiseptic Cream Dual Action (30g)',
    sku: 'GER-30G-BAY',
    description: 'Antiseptic and local anesthetic cream for cuts, grazes, minor burns, and blisters with soothing action.',
    price: '41.00',
    compareAtPrice: '50.00',
    stockQuantity: 100,
    minStockAlert: 10,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Cream',
    strength: '30g',
    activeIngredients: 'Phenol + Chlorhexidine Digluconate',
    manufacturer: 'Bayer',
    categoryName: 'First Aid'
  },
  {
    name: 'Omeprazole 20mg Capsules - Glenmark',
    sku: 'OME-20MG-GLE',
    description: 'Proton pump inhibitor for heartburn, acid indigestion, and peptic ulcer treatment.',
    price: '40.00',
    compareAtPrice: '48.00',
    stockQuantity: 200,
    minStockAlert: 20,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Capsule',
    strength: '20mg',
    activeIngredients: 'Omeprazole',
    manufacturer: 'Glenmark',
    categoryName: 'Gastrointestinal'
  },
  {
    name: 'Omeprazole 20mg Capsules - Almus',
    sku: 'OME-20MG-ALM',
    description: 'Gastro-resistant capsules for gastric acid reduction and ulcer prophylaxis.',
    price: '34.00',
    compareAtPrice: '42.00',
    stockQuantity: 200,
    minStockAlert: 20,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Capsule',
    strength: '20mg',
    activeIngredients: 'Omeprazole',
    manufacturer: 'Almus',
    categoryName: 'Gastrointestinal'
  },
  {
    name: 'Omeprazole 20mg Capsules - Sandoz',
    sku: 'OME-20MG-SAN',
    description: 'Dependable acid reflux and heartburn relief capsules.',
    price: '25.30',
    compareAtPrice: '32.00',
    stockQuantity: 200,
    minStockAlert: 20,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Capsule',
    strength: '20mg',
    activeIngredients: 'Omeprazole',
    manufacturer: 'Sandoz',
    categoryName: 'Gastrointestinal'
  },
  {
    name: 'Solifenacin 10mg Tablets',
    sku: 'SOL-10MG-CRE',
    description: 'Competitive muscarinic receptor antagonist for overactive bladder symptoms with urge incontinence.',
    price: '205.00',
    compareAtPrice: '235.00',
    stockQuantity: 70,
    minStockAlert: 10,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '10mg',
    activeIngredients: 'Solifenacin Succinate',
    manufacturer: 'Crescent Pharma',
    categoryName: 'Men Health'
  },
  {
    name: 'Semaglutide 14mg Tablets (Rybelsus)',
    sku: 'SEM-14MG-RYB',
    description: 'Oral GLP-1 receptor agonist for Type 2 Diabetes glycemic control and weight reduction management.',
    price: '2575.00',
    compareAtPrice: '2850.00',
    stockQuantity: 30,
    minStockAlert: 5,
    requiresPrescription: true,
    isFeatured: true,
    dosageForm: 'Tablet',
    strength: '14mg',
    activeIngredients: 'Semaglutide',
    manufacturer: 'Novo Nordisk / Servipharm',
    categoryName: 'Diabetes Care'
  },
  {
    name: 'Atorvastatin 20mg Tablets - Hillcross',
    sku: 'ATO-20MG-HIL',
    description: 'Statin medication for cholesterol reduction and cardiovascular disease prevention.',
    price: '64.00',
    compareAtPrice: '75.00',
    stockQuantity: 150,
    minStockAlert: 15,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '20mg',
    activeIngredients: 'Atorvastatin Calcium',
    manufacturer: 'Hillcross Pharma',
    categoryName: 'Cardiovascular'
  },
  {
    name: 'Atorvastatin 20mg Tablets - Sandoz',
    sku: 'ATO-20MG-SAN',
    description: 'Standard lipid-lowering therapy for hyperlipidemia and coronary heart disease risk management.',
    price: '45.00',
    compareAtPrice: '55.00',
    stockQuantity: 150,
    minStockAlert: 15,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '20mg',
    activeIngredients: 'Atorvastatin Calcium',
    manufacturer: 'Sandoz',
    categoryName: 'Cardiovascular'
  },
  {
    name: 'Atorvastatin 10mg Tablets - Sandoz',
    sku: 'ATO-10MG-SAN',
    description: 'Initial dose statin for LDL cholesterol reduction.',
    price: '45.00',
    compareAtPrice: '55.00',
    stockQuantity: 150,
    minStockAlert: 15,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '10mg',
    activeIngredients: 'Atorvastatin Calcium',
    manufacturer: 'Sandoz',
    categoryName: 'Cardiovascular'
  },
  {
    name: 'Atorvastatin 10mg Tablets - Flamingo',
    sku: 'ATO-10MG-FLA',
    description: 'Lipid-regulating medication reducing cardiovascular risk factors.',
    price: '41.00',
    compareAtPrice: '50.00',
    stockQuantity: 150,
    minStockAlert: 15,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '10mg',
    activeIngredients: 'Atorvastatin Calcium',
    manufacturer: 'Flamingo Pharma',
    categoryName: 'Cardiovascular'
  },
  {
    name: 'Atorvastatin 10mg Tablets - Sun Pharma',
    sku: 'ATO-10MG-SUN',
    description: 'Affordable cholesterol-lowering medication for cardiovascular wellness.',
    price: '35.00',
    compareAtPrice: '42.00',
    stockQuantity: 150,
    minStockAlert: 15,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '10mg',
    activeIngredients: 'Atorvastatin Calcium',
    manufacturer: 'Sun Pharma',
    categoryName: 'Cardiovascular'
  },
  {
    name: 'Fucidin 2% Cream',
    sku: 'FUC-2PCT-CRM',
    description: 'Topical antibacterial cream targeting primary and secondary skin infections caused by Staph and Strep.',
    price: '125.00',
    compareAtPrice: '145.00',
    stockQuantity: 80,
    minStockAlert: 10,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Cream',
    strength: '2%',
    activeIngredients: 'Fusidic Acid',
    manufacturer: 'Leo Laboratories',
    categoryName: 'Antibiotics'
  },
  {
    name: 'Buscopan 10mg Tablets',
    sku: 'BUS-10MG-OPE',
    description: 'Targeted abdominal cramping and irritable bowel syndrome relief tablets.',
    price: '203.00',
    compareAtPrice: '230.00',
    stockQuantity: 100,
    minStockAlert: 10,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '10mg',
    activeIngredients: 'Hyoscine Butylbromide',
    manufacturer: 'Opella Healthcare / Sanofi',
    categoryName: 'Gastrointestinal'
  },

  // Page 3
  {
    name: 'Bumetanide 1mg Tablets',
    sku: 'BUM-1MG-TEV',
    description: 'Loop diuretic used to treat edema associated with congestive heart failure, hepatic and renal disease.',
    price: '82.00',
    compareAtPrice: '95.00',
    stockQuantity: 90,
    minStockAlert: 10,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '1mg',
    activeIngredients: 'Bumetanide',
    manufacturer: 'Teva',
    categoryName: 'Cardiovascular'
  },
  {
    name: 'Penicillin V 250mg Tablets',
    sku: 'PEN-250-RUD',
    description: 'Oral penicillin antibiotic for streptococcal pharyngitis, skin infections, and rheumatic fever prophylaxis.',
    price: '124.91',
    compareAtPrice: '145.00',
    stockQuantity: 100,
    minStockAlert: 10,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '250mg',
    activeIngredients: 'Phenoxymethylpenicillin Potassium',
    manufacturer: 'Rudi Pharm',
    categoryName: 'Antibiotics'
  },
  {
    name: 'Flucloxacillin 500mg Capsules - Kent',
    sku: 'FLU-500-KEN',
    description: 'Beta-lactamase resistant penicillin antibiotic treating cellulitis, impetigo, and wound infections.',
    price: '139.00',
    compareAtPrice: '160.00',
    stockQuantity: 120,
    minStockAlert: 15,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Capsule',
    strength: '500mg',
    activeIngredients: 'Flucloxacillin Sodium',
    manufacturer: 'Kent Pharma',
    categoryName: 'Antibiotics'
  },
  {
    name: 'Flucloxacillin 500mg Capsules - Medreich',
    sku: 'FLU-500-MED',
    description: 'Staphylococcal infection-fighting antibiotic capsules with high tissue penetration.',
    price: '131.00',
    compareAtPrice: '150.00',
    stockQuantity: 120,
    minStockAlert: 15,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Capsule',
    strength: '500mg',
    activeIngredients: 'Flucloxacillin Sodium',
    manufacturer: 'Medreich',
    categoryName: 'Antibiotics'
  },
  {
    name: 'Ferrous Fumarate 210mg Tablets - Remedy',
    sku: 'FER-FUM-REM',
    description: 'High-elemental iron tablets for prevention and cure of iron-deficiency anemia.',
    price: '74.00',
    compareAtPrice: '85.00',
    stockQuantity: 150,
    minStockAlert: 15,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '210mg',
    activeIngredients: 'Ferrous Fumarate',
    manufacturer: 'Remedy Healthcare',
    categoryName: 'Vitamins & Supplements'
  },
  {
    name: 'Ferrous Fumarate 210mg Tablets - Trion',
    sku: 'FER-FUM-TRI',
    description: 'Oral iron supplement providing elemental iron to boost hemoglobin levels.',
    price: '74.00',
    compareAtPrice: '85.00',
    stockQuantity: 150,
    minStockAlert: 15,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '210mg',
    activeIngredients: 'Ferrous Fumarate',
    manufacturer: 'Trion Pharma',
    categoryName: 'Vitamins & Supplements'
  },
  {
    name: 'Folic Acid 5mg Tablets - Relon Chem',
    sku: 'FOL-5MG-REL',
    description: 'Essential B-vitamin for folate deficiency anemia and neural tube defect prevention in pregnancy.',
    price: '61.00',
    compareAtPrice: '70.00',
    stockQuantity: 200,
    minStockAlert: 20,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '5mg',
    activeIngredients: 'Folic Acid (Vitamin B9)',
    manufacturer: 'Relon Chem',
    categoryName: 'Vitamins & Supplements'
  },
  {
    name: 'Folic Acid 5mg Tablets - Crescent',
    sku: 'FOL-5MG-CRE',
    description: 'High-potency folic acid supplement promoting healthy cell division and RBC development.',
    price: '62.00',
    compareAtPrice: '72.00',
    stockQuantity: 200,
    minStockAlert: 20,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '5mg',
    activeIngredients: 'Folic Acid (Vitamin B9)',
    manufacturer: 'Crescent Pharma',
    categoryName: 'Vitamins & Supplements'
  },
  {
    name: 'Folic Acid 5mg Tablets - Accord',
    sku: 'FOL-5MG-ACC',
    description: 'Affordable daily folate supplementation for prenatal care and hematologic wellness.',
    price: '28.00',
    compareAtPrice: '35.00',
    stockQuantity: 200,
    minStockAlert: 20,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '5mg',
    activeIngredients: 'Folic Acid (Vitamin B9)',
    manufacturer: 'Accord Healthcare',
    categoryName: 'Vitamins & Supplements'
  },
  {
    name: 'Fexofenadine 180mg Tablets',
    sku: 'FEX-180-ZEN',
    description: 'Maximum-strength non-drowsy 24-hour antihistamine for chronic idiopathic urticaria and severe allergies.',
    price: '246.00',
    compareAtPrice: '280.00',
    stockQuantity: 100,
    minStockAlert: 10,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '180mg',
    activeIngredients: 'Fexofenadine Hydrochloride',
    manufacturer: 'Zentiva',
    categoryName: 'Allergy & Cold'
  },
  {
    name: 'Salamol Inhaler 100mcg (CFC-Free)',
    sku: 'SAL-100-IVA',
    description: 'Metered dose Salbutamol inhaler for rapid bronchospasm relief and asthma management.',
    price: '49.89',
    compareAtPrice: '60.00',
    stockQuantity: 150,
    minStockAlert: 15,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Inhaler',
    strength: '100mcg',
    activeIngredients: 'Salbutamol Sulfate',
    manufacturer: 'Ivax Pharmaceuticals / Teva',
    categoryName: 'Respiratory'
  },
  {
    name: 'Finasteride 5mg Tablets',
    sku: 'FIN-5MG-CIP',
    description: '5-alpha reductase inhibitor for benign prostatic hyperplasia (BPH) symptom reduction and urinary flow improvement.',
    price: '163.00',
    compareAtPrice: '185.00',
    stockQuantity: 80,
    minStockAlert: 10,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '5mg',
    activeIngredients: 'Finasteride',
    manufacturer: 'Cipla',
    categoryName: 'Men Health'
  },
  {
    name: 'Metrosa 0.75% Gel (40g)',
    sku: 'MET-075-BEA',
    description: 'Topical metronidazole gel for the treatment of inflammatory papules and pustules of rosacea.',
    price: '459.00',
    compareAtPrice: '510.00',
    stockQuantity: 40,
    minStockAlert: 5,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Gel',
    strength: '0.75% (40g)',
    activeIngredients: 'Metronidazole',
    manufacturer: 'Beaumont Pharma',
    categoryName: 'Personal Care'
  },
  {
    name: 'Hydrocortisone 1% Cream (15g) - Strides',
    sku: 'HYD-1PCT-STR',
    description: 'Mild topical corticosteroid for relief of eczema, dermatitis, insect bites, and allergic skin irritation.',
    price: '69.00',
    compareAtPrice: '80.00',
    stockQuantity: 120,
    minStockAlert: 15,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Cream',
    strength: '1% (15g)',
    activeIngredients: 'Hydrocortisone',
    manufacturer: 'Strides Pharma',
    categoryName: 'Personal Care'
  },
  {
    name: 'Hydrocortisone 1% Cream (15g) - Numark',
    sku: 'HYD-1PCT-NUM',
    description: 'Soothing anti-itch hydrocortisone cream for skin rash and allergic flare-ups.',
    price: '74.00',
    compareAtPrice: '85.00',
    stockQuantity: 120,
    minStockAlert: 15,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Cream',
    strength: '1% (15g)',
    activeIngredients: 'Hydrocortisone',
    manufacturer: 'Numark',
    categoryName: 'Personal Care'
  },
  {
    name: 'Vitamin B Complex Strong Tablets',
    sku: 'VIT-BCO-BEL',
    description: 'High-potency B-complex supplement providing Thiamine (B1), Riboflavin (B2), Nicotinamide (B3), and Pyridoxine (B6).',
    price: '41.00',
    compareAtPrice: '50.00',
    stockQuantity: 200,
    minStockAlert: 20,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: 'Standard',
    activeIngredients: 'Vitamin B Complex (B1, B2, B3, B6)',
    manufacturer: "Bell's Healthcare",
    categoryName: 'Vitamins & Supplements'
  },
  {
    name: 'Hydrocortisone 1% Cream (30g)',
    sku: 'HYD-1PCT-30G',
    description: 'Economy size hydrocortisone cream for larger surface area eczema and inflammatory dermatoses.',
    price: '46.97',
    compareAtPrice: '58.00',
    stockQuantity: 150,
    minStockAlert: 15,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Cream',
    strength: '1% (30g)',
    activeIngredients: 'Hydrocortisone',
    manufacturer: 'Generic',
    categoryName: 'Personal Care'
  },
  {
    name: 'Losartan 50mg Tablets - Ipca',
    sku: 'LOS-50MG-IPC',
    description: 'Angiotensin II receptor blocker (ARB) for hypertension treatment and diabetic nephropathy renal protection.',
    price: '24.00',
    compareAtPrice: '30.00',
    stockQuantity: 180,
    minStockAlert: 20,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '50mg',
    activeIngredients: 'Losartan Potassium',
    manufacturer: 'Ipca Laboratories',
    categoryName: 'Cardiovascular'
  },
  {
    name: 'Losartan 50mg Tablets - Medreich',
    sku: 'LOS-50MG-MED',
    description: 'High-grade ARB blood pressure medication reducing stroke risk in hypertensive patients.',
    price: '180.00',
    compareAtPrice: '205.00',
    stockQuantity: 120,
    minStockAlert: 15,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '50mg',
    activeIngredients: 'Losartan Potassium',
    manufacturer: 'Medreich',
    categoryName: 'Cardiovascular'
  },
  {
    name: 'Losartan 50mg Tablets - Kent Pharma',
    sku: 'LOS-50MG-KEN',
    description: 'Reliable blood pressure medication improving long-term cardiac and kidney outcomes.',
    price: '180.00',
    compareAtPrice: '205.00',
    stockQuantity: 120,
    minStockAlert: 15,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '50mg',
    activeIngredients: 'Losartan Potassium',
    manufacturer: 'Kent Pharma',
    categoryName: 'Cardiovascular'
  },
  {
    name: 'Amoxicillin 250mg/5mL Oral Suspension',
    sku: 'AMX-250-SUS',
    description: 'Broad-spectrum pediatric antibiotic suspension for ear infections, chest infections, and dental abscesses.',
    price: '31.00',
    compareAtPrice: '38.00',
    stockQuantity: 150,
    minStockAlert: 20,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Suspension',
    strength: '250mg/5mL',
    activeIngredients: 'Amoxicillin Trihydrate',
    manufacturer: 'Generic',
    categoryName: 'Antibiotics'
  },
  {
    name: 'Olanzapine 10mg Tablets',
    sku: 'OLA-10MG-GLE',
    description: 'Second-generation atypical antipsychotic for schizophrenia and moderate to severe manic episodes.',
    price: '86.00',
    compareAtPrice: '100.00',
    stockQuantity: 80,
    minStockAlert: 10,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '10mg',
    activeIngredients: 'Olanzapine',
    manufacturer: 'Glenmark',
    categoryName: 'Mental Health'
  },
  {
    name: 'Oestrogel Pump Pack 750mcg/dose (80g)',
    sku: 'OES-750-BES',
    description: 'Transdermal 17-beta estradiol gel for hormone replacement therapy (HRT) alleviating menopausal symptoms.',
    price: '402.00',
    compareAtPrice: '450.00',
    stockQuantity: 50,
    minStockAlert: 5,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Gel',
    strength: '750mcg/dose',
    activeIngredients: 'Estradiol',
    manufacturer: 'Besins Healthcare',
    categoryName: 'Women Health'
  },
  {
    name: 'Ibuprofen 5% Gel (100g) - Mentholatum',
    sku: 'IBU-5PCT-GEL',
    description: 'Deep penetrating topical anti-inflammatory gel providing targeted joint, back, and muscular pain relief.',
    price: '71.00',
    compareAtPrice: '85.00',
    stockQuantity: 120,
    minStockAlert: 15,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Gel',
    strength: '5% (100g)',
    activeIngredients: 'Ibuprofen',
    manufacturer: 'Mentholatum',
    categoryName: 'Pain Relief'
  },
  {
    name: 'Trimethoprim 100mg Tablets',
    sku: 'TRI-100-CRE',
    description: 'Folate antagonist antibiotic indicated for first-line treatment of urinary tract infections (UTIs).',
    price: '115.00',
    compareAtPrice: '130.00',
    stockQuantity: 100,
    minStockAlert: 10,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '100mg',
    activeIngredients: 'Trimethoprim',
    manufacturer: 'Crescent Pharma',
    categoryName: 'Antibiotics'
  },
  {
    name: 'Tamsulosin 400mcg MR Capsules - Hillcross',
    sku: 'TAM-400-HIL',
    description: 'Alpha-1A adrenoceptor blocker for rapid relief of lower urinary tract symptoms in benign prostatic hyperplasia.',
    price: '139.00',
    compareAtPrice: '160.00',
    stockQuantity: 100,
    minStockAlert: 10,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Capsule',
    strength: '400mcg',
    activeIngredients: 'Tamsulosin Hydrochloride',
    manufacturer: 'Hillcross Pharma',
    categoryName: 'Men Health'
  },
  {
    name: 'Tamsulosin 400mcg MR Capsules - Zentiva',
    sku: 'TAM-400-ZEN',
    description: 'Modified-release prostate medication improving urinary stream and reducing nighttime voiding.',
    price: '139.00',
    compareAtPrice: '160.00',
    stockQuantity: 100,
    minStockAlert: 10,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Capsule',
    strength: '400mcg',
    activeIngredients: 'Tamsulosin Hydrochloride',
    manufacturer: 'Zentiva',
    categoryName: 'Men Health'
  },
  {
    name: 'Clopidogrel 75mg Tablets - Zentiva',
    sku: 'CLO-75MG-ZEN',
    description: 'P2Y12 platelet inhibitor used to prevent atherothrombotic events following stent placement or stroke.',
    price: '47.00',
    compareAtPrice: '58.00',
    stockQuantity: 150,
    minStockAlert: 15,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '75mg',
    activeIngredients: 'Clopidogrel Bisulfate',
    manufacturer: 'Zentiva',
    categoryName: 'Cardiovascular'
  },
  {
    name: 'Thiamine 100mg Tablets (Vitamin B1)',
    sku: 'THI-100-BIO',
    description: 'High-dose Vitamin B1 supplement treating thiamine deficiency, neuropathy, and supporting carbohydrate metabolism.',
    price: '74.00',
    compareAtPrice: '85.00',
    stockQuantity: 150,
    minStockAlert: 15,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '100mg',
    activeIngredients: 'Thiamine Hydrochloride',
    manufacturer: 'BioVantic Pharma',
    categoryName: 'Vitamins & Supplements'
  },
  {
    name: 'Sildenafil 25mg Tablets - Amarox',
    sku: 'SIL-25MG-AMA',
    description: 'PDE5 inhibitor starting dose for erectile dysfunction treatment.',
    price: '122.00',
    compareAtPrice: '140.00',
    stockQuantity: 80,
    minStockAlert: 10,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '25mg',
    activeIngredients: 'Sildenafil Citrate',
    manufacturer: 'Amarox Pharma',
    categoryName: 'Men Health'
  },
  {
    name: 'Sildenafil 25mg Tablets - Milpharm',
    sku: 'SIL-25MG-MIL',
    description: 'Phosphodiesterase type 5 inhibitor for men health and erectile performance.',
    price: '130.00',
    compareAtPrice: '150.00',
    stockQuantity: 80,
    minStockAlert: 10,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '25mg',
    activeIngredients: 'Sildenafil Citrate',
    manufacturer: 'Milpharm Limited',
    categoryName: 'Men Health'
  },
  {
    name: 'Sildenafil 50mg Tablets - Dr. Reddys',
    sku: 'SIL-50MG-DRR',
    description: 'Standard effective dose PDE5 inhibitor for erectile dysfunction management.',
    price: '54.00',
    compareAtPrice: '65.00',
    stockQuantity: 120,
    minStockAlert: 15,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '50mg',
    activeIngredients: 'Sildenafil Citrate',
    manufacturer: "Dr. Reddy's Laboratories",
    categoryName: 'Men Health'
  },
  {
    name: 'Sildenafil 50mg Tablets - Lekap',
    sku: 'SIL-50MG-LEK',
    description: 'Affordable quality sildenafil citrate tablets for male wellness.',
    price: '35.00',
    compareAtPrice: '45.00',
    stockQuantity: 120,
    minStockAlert: 15,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '50mg',
    activeIngredients: 'Sildenafil Citrate',
    manufacturer: 'Lekap Pharma',
    categoryName: 'Men Health'
  },
  {
    name: 'Senna 7.5mg Tablets',
    sku: 'SEN-75MG-TAB',
    description: 'Natural anthraquinone stimulant laxative providing overnight relief from occasional constipation.',
    price: '120.00',
    compareAtPrice: '140.00',
    stockQuantity: 180,
    minStockAlert: 20,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '7.5mg',
    activeIngredients: 'Sennosides',
    manufacturer: 'Generic',
    categoryName: 'Gastrointestinal'
  },
  {
    name: 'Nitrofurantoin 100mg Prolonged Release Capsules',
    sku: 'NIT-100-MER',
    description: 'First-choice antibiotic for acute uncomplicated urinary tract infections and cystitis.',
    price: '210.00',
    compareAtPrice: '240.00',
    stockQuantity: 90,
    minStockAlert: 10,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Capsule',
    strength: '100mg',
    activeIngredients: 'Nitrofurantoin',
    manufacturer: 'Mercury Pharma',
    categoryName: 'Antibiotics'
  },
  {
    name: 'Amoxicillin 500mg Capsules - Brown & Burk',
    sku: 'AMX-500-BRN',
    description: 'High-potency broad-spectrum aminopenicillin for chest, ear, throat, and sinus infections.',
    price: '46.00',
    compareAtPrice: '55.00',
    stockQuantity: 200,
    minStockAlert: 20,
    requiresPrescription: true,
    isFeatured: true,
    dosageForm: 'Capsule',
    strength: '500mg',
    activeIngredients: 'Amoxicillin Trihydrate',
    manufacturer: 'Brown & Burk',
    categoryName: 'Antibiotics'
  },
  {
    name: 'Amoxicillin 500mg Capsules - Medreich',
    sku: 'AMX-500-MED',
    description: 'Reliable antibacterial capsules treating broad bacterial infections.',
    price: '46.00',
    compareAtPrice: '55.00',
    stockQuantity: 200,
    minStockAlert: 20,
    requiresPrescription: true,
    isFeatured: true,
    dosageForm: 'Capsule',
    strength: '500mg',
    activeIngredients: 'Amoxicillin Trihydrate',
    manufacturer: 'Medreich',
    categoryName: 'Antibiotics'
  },

  // Page 4
  {
    name: 'Inhixa 8000iu (80mg/0.8mL) Pre-filled Syringes',
    sku: 'INH-8000-SYR',
    description: 'Low molecular weight heparin (LMWH) anticoagulant for treatment of DVT, pulmonary embolism, and acute coronary syndrome.',
    price: '804.00',
    compareAtPrice: '880.00',
    stockQuantity: 40,
    minStockAlert: 5,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Injection',
    strength: '8000iu (80mg/0.8mL)',
    activeIngredients: 'Enoxaparin Sodium',
    manufacturer: 'Techdow Pharma',
    categoryName: 'Cardiovascular'
  },
  {
    name: 'Inhixa 6000iu (60mg/0.6mL) Pre-filled Syringes',
    sku: 'INH-6000-SYR',
    description: 'Enoxaparin pre-filled syringes for therapeutic anticoagulation and thrombosis prevention.',
    price: '607.00',
    compareAtPrice: '670.00',
    stockQuantity: 40,
    minStockAlert: 5,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Injection',
    strength: '6000iu (60mg/0.6mL)',
    activeIngredients: 'Enoxaparin Sodium',
    manufacturer: 'Techdow Pharma',
    categoryName: 'Cardiovascular'
  },
  {
    name: 'Gaviscon Advance Chewable Tablets',
    sku: 'GAV-ADV-TAB',
    description: 'Extra-strength alginate formula forming a robust physical barrier to block acid reflux and soothe heartburn.',
    price: '144.00',
    compareAtPrice: '165.00',
    stockQuantity: 120,
    minStockAlert: 15,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: 'Standard',
    activeIngredients: 'Sodium Alginate + Potassium Bicarbonate',
    manufacturer: 'Reckitt Benckiser',
    categoryName: 'Gastrointestinal'
  },
  {
    name: 'Levonorgestrel 1.5mg Emergency Contraceptive - Clydesdale',
    sku: 'LEV-15MG-CLY',
    description: 'Single-tablet morning-after emergency contraception effective up to 72 hours post-unprotected intercourse.',
    price: '74.00',
    compareAtPrice: '85.00',
    stockQuantity: 100,
    minStockAlert: 10,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '1.5mg',
    activeIngredients: 'Levonorgestrel',
    manufacturer: 'Clydesdale Pharma Ltd',
    categoryName: 'Women Health'
  },
  {
    name: 'Levonorgestrel 1.5mg Emergency Contraceptive - Relon Chem',
    sku: 'LEV-15MG-REL',
    description: 'Emergency contraceptive pill preventing pregnancy within 72 hours of unprotected intercourse.',
    price: '74.00',
    compareAtPrice: '85.00',
    stockQuantity: 100,
    minStockAlert: 10,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '1.5mg',
    activeIngredients: 'Levonorgestrel',
    manufacturer: 'Relon Chem',
    categoryName: 'Women Health'
  },
  {
    name: 'Eva One 1.5mg Emergency Contraceptive Tablet',
    sku: 'EVA-ONE-TAB',
    description: 'Rapid-acting emergency contraception tablet with proven efficacy and high safety profile.',
    price: '35.00',
    compareAtPrice: '42.00',
    stockQuantity: 150,
    minStockAlert: 15,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '1.5mg',
    activeIngredients: 'Levonorgestrel',
    manufacturer: 'Eva Pharma',
    categoryName: 'Women Health'
  },
  {
    name: 'Safe & Sound First Aid Plasters Pack',
    sku: 'SAF-SND-PLA',
    description: 'Breathable, hypoallergenic adhesive plasters in assorted sizes for minor cuts and wound protection.',
    price: '49.00',
    compareAtPrice: '58.00',
    stockQuantity: 150,
    minStockAlert: 15,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Plaster',
    strength: 'Assorted Pack',
    activeIngredients: 'Adhesive Dressing Material',
    manufacturer: 'Safe & Sound',
    categoryName: 'First Aid'
  },
  {
    name: 'Esomeprazole 20mg Capsules - Mylan',
    sku: 'ESO-20MG-MYL',
    description: 'Daily proton pump inhibitor for heartburn prevention, acid reflux control, and stomach comfort.',
    price: '131.00',
    compareAtPrice: '150.00',
    stockQuantity: 120,
    minStockAlert: 15,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Capsule',
    strength: '20mg',
    activeIngredients: 'Esomeprazole Magnesium',
    manufacturer: 'Mylan / Viatris',
    categoryName: 'Gastrointestinal'
  },
  {
    name: 'Prednisolone 5mg Tablets - Relon Chem',
    sku: 'PRE-5MG-REL',
    description: 'Glucocorticoid steroid for suppressing severe allergic reactions, asthma exacerbations, and inflammatory flares.',
    price: '57.00',
    compareAtPrice: '68.00',
    stockQuantity: 150,
    minStockAlert: 15,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '5mg',
    activeIngredients: 'Prednisolone',
    manufacturer: 'Relon Chem',
    categoryName: 'Personal Care'
  },
  {
    name: 'Prednisolone 5mg Tablets - Accord',
    sku: 'PRE-5MG-ACC',
    description: 'Systemic corticosteroid tablet managing acute inflammatory and autoimmune conditions.',
    price: '57.00',
    compareAtPrice: '68.00',
    stockQuantity: 150,
    minStockAlert: 15,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '5mg',
    activeIngredients: 'Prednisolone',
    manufacturer: 'Accord Healthcare',
    categoryName: 'Personal Care'
  },
  {
    name: 'Prednisolone 5mg Suppositories',
    sku: 'PRE-5MG-SUP',
    description: 'Rectal steroid suppositories for targeted treatment of ulcerative proctitis and local rectal inflammation.',
    price: '4476.67',
    compareAtPrice: '4800.00',
    stockQuantity: 20,
    minStockAlert: 2,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Suppository',
    strength: '5mg',
    activeIngredients: 'Prednisolone',
    manufacturer: 'Pharm AB',
    categoryName: 'Personal Care'
  },
  {
    name: 'Prednisolone 1mg Tablets - Wockhardt',
    sku: 'PRE-1MG-WOC',
    description: 'Low-strength prednisolone for precise tapering protocols in chronic autoimmune diseases.',
    price: '69.00',
    compareAtPrice: '80.00',
    stockQuantity: 100,
    minStockAlert: 10,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '1mg',
    activeIngredients: 'Prednisolone',
    manufacturer: 'Wockhardt',
    categoryName: 'Personal Care'
  },
  {
    name: 'Prednisolone 1mg Tablets - Accord',
    sku: 'PRE-1MG-ACC',
    description: 'Micro-dose corticosteroid enabling accurate dose titration and steroid withdrawal management.',
    price: '69.00',
    compareAtPrice: '80.00',
    stockQuantity: 100,
    minStockAlert: 10,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '1mg',
    activeIngredients: 'Prednisolone',
    manufacturer: 'Accord Healthcare',
    categoryName: 'Personal Care'
  },
  {
    name: 'Glycerol 4g Adult Suppositories',
    sku: 'GLY-4G-SUP',
    description: 'Gentle hyperosmotic rectal laxative stimulating rapid bowel evacuation within 15-30 minutes.',
    price: '66.00',
    compareAtPrice: '78.00',
    stockQuantity: 120,
    minStockAlert: 15,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Suppository',
    strength: '4g',
    activeIngredients: 'Glycerol (Glycerin)',
    manufacturer: 'Martindale Pharma',
    categoryName: 'Gastrointestinal'
  },
  {
    name: 'Water for Injection (10x10mL Ampoules) - Suhavi',
    sku: 'WFI-10X10-SUH',
    description: 'Pack of 10 sterile ampoules (10mL each) for hospital and clinic drug reconstitution.',
    price: '35.00',
    compareAtPrice: '42.00',
    stockQuantity: 150,
    minStockAlert: 15,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Injection',
    strength: '10x10mL',
    activeIngredients: 'Sterile Water for Injection',
    manufacturer: 'Suhavi Pharma',
    categoryName: 'Medical Supplies'
  },
  {
    name: 'Glucogel 40% Dextrose Gel (3x25g)',
    sku: 'GLU-40PCT-GEL',
    description: 'Fast-acting oral glucose gel tubes for the immediate emergency rescue of hypoglycemic episodes.',
    price: '144.00',
    compareAtPrice: '165.00',
    stockQuantity: 60,
    minStockAlert: 10,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Gel',
    strength: '40% (3x25g)',
    activeIngredients: 'Dextrose (Glucose)',
    manufacturer: 'BBI Healthcare',
    categoryName: 'Diabetes Care'
  },
  {
    name: 'Rosuvastatin 10mg Tablets - Teva',
    sku: 'ROS-10MG-TEV',
    description: 'High-efficacy statin for primary and secondary prevention of atherosclerotic cardiovascular disease.',
    price: '212.80',
    compareAtPrice: '240.00',
    stockQuantity: 100,
    minStockAlert: 10,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '10mg',
    activeIngredients: 'Rosuvastatin Calcium',
    manufacturer: 'Teva',
    categoryName: 'Cardiovascular'
  },
  {
    name: 'Canesten HC Cream (30g)',
    sku: 'CAN-HC-30G',
    description: 'Dual action antifungal & hydrocortisone cream for inflamed fungal skin infections, jock itch, and sweat rash.',
    price: '152.00',
    compareAtPrice: '175.00',
    stockQuantity: 80,
    minStockAlert: 10,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Cream',
    strength: '30g',
    activeIngredients: 'Clotrimazole 1% + Hydrocortisone 1%',
    manufacturer: 'Bayer',
    categoryName: 'Personal Care'
  },
  {
    name: 'Enoxaparin Sodium 4000iu (40mg/0.4mL) Syringes',
    sku: 'ENO-4000-SYR',
    description: 'LMWH pre-filled syringe for venous thromboembolism prophylaxis in surgical and medical patients.',
    price: '450.00',
    compareAtPrice: '500.00',
    stockQuantity: 50,
    minStockAlert: 5,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Injection',
    strength: '4000iu (40mg/0.4mL)',
    activeIngredients: 'Enoxaparin Sodium',
    manufacturer: 'Sanofi / Generic',
    categoryName: 'Cardiovascular'
  },
  {
    name: 'Cyanocobalamin 50mcg Tablets (Vitamin B12)',
    sku: 'CYA-50MCG-REM',
    description: 'Essential Vitamin B12 supplement for nerve function, DNA synthesis, and red blood cell production.',
    price: '41.00',
    compareAtPrice: '50.00',
    stockQuantity: 150,
    minStockAlert: 15,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '50mcg',
    activeIngredients: 'Cyanocobalamin',
    manufacturer: 'Remedy Pharm',
    categoryName: 'Vitamins & Supplements'
  },
  {
    name: 'Reliwipe Sterile Saline Wound Cleansing Wipes',
    sku: 'REL-WND-WIP',
    description: 'Sterile individual saline wipes for gentle, sting-free cleaning of wounds, grazes, and skin before dressing.',
    price: '139.00',
    compareAtPrice: '160.00',
    stockQuantity: 100,
    minStockAlert: 10,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Cleansing Wipes',
    strength: 'Pack of 100',
    activeIngredients: '0.9% Sterile Sodium Chloride',
    manufacturer: 'Reliance Medical',
    categoryName: 'First Aid'
  },
  {
    name: 'Zovirax Cold Sore Cream (2g)',
    sku: 'ZOV-CS-2G',
    description: 'Targeted aciclovir antiviral cream speeding up cold sore healing and halting virus replication.',
    price: '139.00',
    compareAtPrice: '160.00',
    stockQuantity: 100,
    minStockAlert: 10,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Cream',
    strength: '5% (2g)',
    activeIngredients: 'Aciclovir',
    manufacturer: 'Haleon / GSK',
    categoryName: 'Personal Care'
  },
  {
    name: 'Glyceryl Trinitrate (GTN) 400mcg Sublingual Spray',
    sku: 'GTN-400-SPR',
    description: 'Sublingual pump spray for rapid relief and prophylaxis of angina pectoris attacks.',
    price: '147.00',
    compareAtPrice: '170.00',
    stockQuantity: 80,
    minStockAlert: 10,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Spray',
    strength: '400mcg/dose',
    activeIngredients: 'Glyceryl Trinitrate',
    manufacturer: 'Accord Healthcare',
    categoryName: 'Cardiovascular'
  },
  {
    name: 'Numark Antiseptic Cleansing Wipes',
    sku: 'NUM-ANT-WIP',
    description: 'Individually wrapped antiseptic cleansing wipes for first-aid skin sanitization.',
    price: '173.43',
    compareAtPrice: '200.00',
    stockQuantity: 100,
    minStockAlert: 10,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Cleansing Wipes',
    strength: 'Pack of 100',
    activeIngredients: 'Chlorhexidine + Cetrimide',
    manufacturer: 'Numark',
    categoryName: 'First Aid'
  },
  {
    name: 'Dexamethasone / Neomycin Drops (Maxitrol)',
    sku: 'DEX-NEO-DRP',
    description: 'Combination steroid and aminoglycoside antibiotic drops for inflammatory ocular and aural infections.',
    price: '54.00',
    compareAtPrice: '65.00',
    stockQuantity: 90,
    minStockAlert: 10,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Eye Drops',
    strength: '5mL',
    activeIngredients: 'Dexamethasone + Neomycin Sulfate',
    manufacturer: 'Novartis',
    categoryName: 'Eye Care'
  },
  {
    name: '3M Steri-Strip Skin Closures',
    sku: '3M-STR-STP',
    description: 'Adhesive skin closure strips providing wound support and enhanced healing for lacerations and surgical incisions.',
    price: '180.00',
    compareAtPrice: '210.00',
    stockQuantity: 100,
    minStockAlert: 10,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Plaster',
    strength: 'Assorted Strips',
    activeIngredients: 'Non-woven Porous Surgical Material',
    manufacturer: '3M Health Care',
    categoryName: 'First Aid'
  },
  {
    name: 'Tramadol 50mg Capsules',
    sku: 'TRA-50MG-SOM',
    description: 'Centrally acting opioid analgesic for the management of moderate to severe acute and chronic pain.',
    price: '80.00',
    compareAtPrice: '95.00',
    stockQuantity: 80,
    minStockAlert: 10,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Capsule',
    strength: '50mg',
    activeIngredients: 'Tramadol Hydrochloride',
    manufacturer: 'Somex Pharma',
    categoryName: 'Pain Relief'
  },
  {
    name: 'Bendroflumethiazide 2.5mg Tablets',
    sku: 'BEN-25-CRE',
    description: 'Thiazide diuretic for essential hypertension and mild cardiac edema management.',
    price: '11.80',
    compareAtPrice: '16.00',
    stockQuantity: 200,
    minStockAlert: 20,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '2.5mg',
    activeIngredients: 'Bendroflumethiazide',
    manufacturer: 'Crescent Pharma',
    categoryName: 'Cardiovascular'
  },
  {
    name: 'Gliclazide 80mg Tablets - Crescent Pack',
    sku: 'GLI-80MG-CR2',
    description: 'Oral sulfonylurea promoting endogenous insulin release in Type 2 Diabetes.',
    price: '139.00',
    compareAtPrice: '160.00',
    stockQuantity: 150,
    minStockAlert: 15,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '80mg',
    activeIngredients: 'Gliclazide',
    manufacturer: 'Crescent Pharma',
    categoryName: 'Diabetes Care'
  },
  {
    name: 'Metformin 500mg Tablets - Glenmark',
    sku: 'MET-500-GLE',
    description: 'Antidiabetic tablet controlling blood sugar spikes and improving insulin sensitivity.',
    price: '35.00',
    compareAtPrice: '42.00',
    stockQuantity: 200,
    minStockAlert: 20,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '500mg',
    activeIngredients: 'Metformin Hydrochloride',
    manufacturer: 'Glenmark',
    categoryName: 'Diabetes Care'
  },
  {
    name: 'Laxido Orange Oral Powder Sachets (30s)',
    sku: 'LAX-ORG-30S',
    description: 'Macrogol osmotic laxative with balanced electrolytes for chronic constipation and fecal impaction.',
    price: '184.00',
    compareAtPrice: '210.00',
    stockQuantity: 80,
    minStockAlert: 10,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Powder',
    strength: '30 Sachets',
    activeIngredients: 'Macrogol 3350 + Electrolytes',
    manufacturer: 'Galen Limited',
    categoryName: 'Gastrointestinal'
  },
  {
    name: 'Vagisil Medicated Creme (30g)',
    sku: 'VAG-MED-30G',
    description: 'Fast-acting soothing cream with anesthetic properties for external feminine itching and irritation.',
    price: '91.00',
    compareAtPrice: '105.00',
    stockQuantity: 90,
    minStockAlert: 10,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Cream',
    strength: '30g',
    activeIngredients: 'Lidocaine 2%',
    manufacturer: 'Combe / Vagisil',
    categoryName: 'Women Health'
  },
  {
    name: 'Salofalk 500mg Gastro-Resistant Tablets',
    sku: 'SAL-500-FAL',
    description: 'Aminosalicylate anti-inflammatory for acute episodes and maintenance remission of Ulcerative Colitis.',
    price: '885.00',
    compareAtPrice: '960.00',
    stockQuantity: 40,
    minStockAlert: 5,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '500mg',
    activeIngredients: 'Mesalazine',
    manufacturer: 'Dr. Falk Pharma',
    categoryName: 'Gastrointestinal'
  },
  {
    name: 'Sanatogen A-Z Complete Multivitamins',
    sku: 'SAN-AZ-TAB',
    description: 'Comprehensive daily formulation of 23 essential vitamins and minerals supporting immunity, energy, and vitality.',
    price: '246.00',
    compareAtPrice: '280.00',
    stockQuantity: 100,
    minStockAlert: 10,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: 'Standard',
    activeIngredients: 'Multivitamins & Minerals Formulation',
    manufacturer: 'Bayer / Sanatogen',
    categoryName: 'Vitamins & Supplements'
  },
  {
    name: 'Bisoprolol 2.5mg Tablets - Ipca',
    sku: 'BIS-25MG-IPC',
    description: 'Low-dose cardioselective beta-blocker for gentle blood pressure control and mild heart failure titration.',
    price: '35.00',
    compareAtPrice: '42.00',
    stockQuantity: 150,
    minStockAlert: 15,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '2.5mg',
    activeIngredients: 'Bisoprolol Fumarate',
    manufacturer: 'Ipca Laboratories',
    categoryName: 'Cardiovascular'
  },
  {
    name: 'Lansoprazole 15mg Capsules - Milpharm',
    sku: 'LAN-15MG-MIL',
    description: 'Proton pump inhibitor maintaining healing of reflux esophagitis and suppressing gastric acid secretion.',
    price: '139.00',
    compareAtPrice: '160.00',
    stockQuantity: 120,
    minStockAlert: 15,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Capsule',
    strength: '15mg',
    activeIngredients: 'Lansoprazole',
    manufacturer: 'Milpharm Limited',
    categoryName: 'Gastrointestinal'
  },
  {
    name: 'Cortiment 9mg Prolonged-Release Tablets',
    sku: 'COR-9MG-FER',
    description: 'Locally acting oral budesonide tablet targeting colonic inflammation in mild to moderate ulcerative colitis.',
    price: '1570.00',
    compareAtPrice: '1720.00',
    stockQuantity: 30,
    minStockAlert: 5,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '9mg',
    activeIngredients: 'Budesonide',
    manufacturer: 'Ferring Pharmaceuticals',
    categoryName: 'Gastrointestinal'
  },
  {
    name: 'Elastoplast Fabric Elastic Plasters',
    sku: 'ELA-FAB-PLA',
    description: 'Heavy fabric adhesive dressing adapting to body movements with strong adhesion and wound pad cushioning.',
    price: '65.00',
    compareAtPrice: '75.00',
    stockQuantity: 150,
    minStockAlert: 15,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Plaster',
    strength: 'Assorted Pack',
    activeIngredients: 'Elastic Fabric Dressing Material',
    manufacturer: 'Beiersdorf',
    categoryName: 'First Aid'
  },
  {
    name: 'Carvedilol 12.5mg Tablets - Milpharm',
    sku: 'CAR-125-MIL',
    description: 'Dual alpha- and non-selective beta-blocker for comprehensive blood pressure lowering and congestive heart failure therapy.',
    price: '32.00',
    compareAtPrice: '40.00',
    stockQuantity: 120,
    minStockAlert: 15,
    requiresPrescription: true,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '12.5mg',
    activeIngredients: 'Carvedilol',
    manufacturer: 'Milpharm Limited',
    categoryName: 'Cardiovascular'
  },

  // Page 5
  {
    name: 'Hyabak 0.15% Eye Drops (10mL)',
    sku: 'HYA-015-10ML',
    description: 'Preservative-free hypotonic sodium hyaluronate artificial tears compatible with all contact lenses.',
    price: '193.00',
    compareAtPrice: '220.00',
    stockQuantity: 70,
    minStockAlert: 10,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Eye Drops',
    strength: '0.15% (10mL)',
    activeIngredients: 'Sodium Hyaluronate',
    manufacturer: 'Thea Laboratories',
    categoryName: 'Eye Care'
  },
  {
    name: 'CENLAX Calcium Sennosides 7.5mg Tablets',
    sku: 'CEN-75MG-MAN',
    description: 'Gentle botanical laxative providing predictable overnight relief from constipation.',
    price: '41.00',
    compareAtPrice: '50.00',
    stockQuantity: 120,
    minStockAlert: 15,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '7.5mg',
    activeIngredients: 'Calcium Sennosides',
    manufacturer: 'Manx Healthcare',
    categoryName: 'Gastrointestinal'
  },
  {
    name: 'Sennosides 7.5mg Tablets - Dawa',
    sku: 'SEN-75MG-DAW',
    description: 'Standardized herbal sennosides promoting natural intestinal motility and bowel relief.',
    price: '24.00',
    compareAtPrice: '30.00',
    stockQuantity: 150,
    minStockAlert: 15,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '7.5mg',
    activeIngredients: 'Sennosides',
    manufacturer: 'Dawa Limited',
    categoryName: 'Gastrointestinal'
  },
  {
    name: 'Sennosides 7.5mg Tablets - Alissa',
    sku: 'SEN-75MG-ALI',
    description: 'Reliable stimulant laxative tablets for sluggish digestion and irregularity.',
    price: '41.00',
    compareAtPrice: '50.00',
    stockQuantity: 120,
    minStockAlert: 15,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Tablet',
    strength: '7.5mg',
    activeIngredients: 'Sennosides',
    manufacturer: 'Alissa Healthcare',
    categoryName: 'Gastrointestinal'
  },
  {
    name: 'Accu-Chek FastClix Lancets (102s)',
    sku: 'ACC-FCL-102',
    description: '1-click lancet drums (6 lancets per drum, 17 drums = 102 lancets) with Clixmotion technology for virtually pain-free blood testing.',
    price: '344.00',
    compareAtPrice: '380.00',
    stockQuantity: 60,
    minStockAlert: 10,
    requiresPrescription: false,
    isFeatured: false,
    dosageForm: 'Diagnostic',
    strength: '102 Lancets',
    activeIngredients: 'Sterile Surgical Stainless Steel Lancets',
    manufacturer: 'Roche Diabetes Care',
    categoryName: 'Diabetes Care'
  }
];

function escapeCsv(val) {
  if (val === null || val === undefined) return '';
  const str = String(val);
  if (str.includes(',') || str.includes('\"') || str.includes('\n')) {
    return '\"' + str.replace(/\"/g, '\"\"') + '\"';
  }
  return str;
}

const headers = [
  'name',
  'sku',
  'description',
  'price',
  'compareAtPrice',
  'stockQuantity',
  'minStockAlert',
  'requiresPrescription',
  'isFeatured',
  'dosageForm',
  'strength',
  'activeIngredients',
  'manufacturer',
  'categoryName'
];

const csvRows = [headers.join(',')];

for (const item of rawItems) {
  const row = [
    escapeCsv(item.name),
    escapeCsv(item.sku),
    escapeCsv(item.description),
    escapeCsv(item.price),
    escapeCsv(item.compareAtPrice),
    escapeCsv(item.stockQuantity),
    escapeCsv(item.minStockAlert),
    escapeCsv(item.requiresPrescription),
    escapeCsv(item.isFeatured),
    escapeCsv(item.dosageForm),
    escapeCsv(item.strength),
    escapeCsv(item.activeIngredients),
    escapeCsv(item.manufacturer),
    escapeCsv(item.categoryName)
  ];
  csvRows.push(row.join(','));
}

const csvOutput = csvRows.join('\n');
const outputPath = path.resolve(__dirname, '..', 'drug_price_list_pharm_philip.csv');
fs.writeFileSync(outputPath, csvOutput, 'utf8');
console.log('Successfully generated ' + rawItems.length + ' products in CSV matching target schema at: ' + outputPath);
